# Change these first  ... https://upptime.js.org/docs/configuration/
owner:  Xiija
repo:   UpMonitor

# Add your sites here
sites:
  - name: Bolo
    url:  https://Bolo.tikihed.repl.co
  - name: Dr.Klahn
    url:  https://Dr-Klahn.tikihed.repl.co
  - name: Zoltar
    url:  https://Zoltar-12.tikihed.repl.co  
  - name: Prometheus
    url:  https://Prometheus-1.tikihed.repl.co
  - name: DeathBot K
    url:  https://DeathBot-K.tikihed.repl.co 
  - name: SecondLife RDB
    url:  https://SecondLife-RDB-1.tikihed.repl.co  
  - name: ChatLogr
    url:  https://http-resp-6-chatLogr-1.tikihed.repl.co
  - name: MBOT-4
    url:  https://MBOT-4.tikihed.repl.co   
   
  
  # - name: Google
  #   url: https://www.google.com
  #   icon: https://www.google.com/favicon.ico   
 

status-website:
  # js: "window.open = function() { alert('Hello!') }"
  #theme: night # light dark night ocean
  themeUrl: https://Xiija.github.io/css/khaki.css
  favicon:  https://plantpathco.com/wp-content/uploads/2020/01/favicon.png
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /UpMonitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: UpMonitor Status Home
  introTitle: "**UpMonitor Status Page**"
  introMessage:  A Monitor for Tiki's bots <br> [**Get your own for free**](https://upptime.js.org/docs/get-started)
  navbar:
    - title: Matrix Screensaver
      href: https://xiija.github.io/MAIN/Matrix1-1-4/index.html
    - title: My UpMonitor Github Repo
      href: https://github.com/Xiija/UpMonitor

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

# user-agent: your-github-username
